language: rust
rust:
    - nightly
    - 1.0.0-beta
notifications:
    email:
        - mitchell.nordine@gmail.com
os:
    - osx
matrix:
  allow_failures:
    - os: linux
env:
    - LD_LIBRARY_PATH: /usr/local/lib
before_script:
    - rustc --version
    - cargo --version
script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo doc --verbose
